version: '3.7'

services:
  postgres-db:
    container_name: 'ic-db-postgres'
    image: postgres:14.5
    restart: always
    ports:
      - '5432:5432'
    # volumes:
    #   - ./postgres_dev:/var/lib/postgresql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
